name: House Keeping
on:
  workflow_dispatch:
    inputs:
      query:
        description: "Query params for house keeping endpoint"
        required: false
  schedule:
    - cron: "0 6 * * *" # Every day at 6:00am UTC

jobs:
  clean:
    name: "Clean"
    runs-on: ubuntu-latest
    steps:
      - name: Call house keeping
        env:
          API_SECRET: ${{ secrets.API_SECRET }}
        run: |
          curl -X "POST" --fail "https://rallly.co/api/house-keeping${{ github.event.inputs.query }}" \
          -H "Authorization: Bearer ${API_SECRET}"
